#!/data/data/com.termux/files/usr/bin/bash

# Used to delay after showing an error.
function fail() {
	printf "${1}" >&2
	sleep 5
	exit 1
}

# Exit if youtube-dl cannot be run
if ! youtube-dl --version &>/dev/null; then
	fail "\e[031m Please install Youtube-dl manualy or run the the install.sh script again.\e[0m\n"
	exit 1
fi

# Clear the screen and display the menu
clear
printf '\e[031m           ▄▀▄     ▄▀▄\n'
printf '\e[031m          ▄█░░▀▀▀▀▀░░█▄\n'
printf '\e[031m      ▄▄  █░░░░░░░░░░░█  ▄▄\n'
printf '\e[031m     █▄▄█ █░░█░░┬░░█░░█ █▄▄█\n'
printf '\e[036m ╔════════════════════════════════════════╗\n'
printf '\e[032m ║ ♚ Project Name : 🆃🅴🆁🅼🆄🆇-🆈🆃🅳™           ║\n'
printf '\e[032m ║ ♚ Author : KhanSaad1275                ║\n'
printf '\e[032m ║ ♚ Github : g̲i̲t̲h̲u̲b̲.̲c̲o̲m̲/̲k̲h̲a̲n̲s̲a̲a̲d̲1̲2̲7̲5̲/̲    ║\n'
printf '\e[032m ║ ♚ Website : www.LearnTermux.tech       ║\n'
printf '\e[036m ╠════════════════════════════════════════╝\n'
printf '\e[036m ╠═▶ [𝗦𝗲𝗹𝗲𝗰𝘁 𝗔 𝗙𝗼𝗿𝗺𝗮𝘁]  ➳\n'
printf '\e[032m ╠═▶ 1. Music Mp3♫\n'
printf '\e[032m ╠═▶ 2. Video 360p\n'
printf '\e[032m ╠═▶ 3. Video 480p\n'
printf '\e[032m ╠═▶ 4. Video 720p\n'
printf '\e[032m ╠═▶ 5. Video 1080p\n'
printf '\e[032m ╠═▶ 6. Video 2160p\n'
printf '\e[032m ╠═▶ 7. Exit Termux-YTD\n'
printf '\e[032m ╚═:➤  \e[0m\n'
command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/Termux-YTD/%(title)s.%(ext)s -i -f'

# Read user input
read -r option

# Check that an option was chosen
if [[ -z ${option} ]]; then
	clear
	fail '\e[031m Please choose a option!\e[0m\n'
	exit 1
else
	# Parse the user input
	case "${option}" in
		1) printf '%s 140\n' "${command}";;                    # Music MP3
		2) printf '%s \"best[height<=360]\"\n' "${command}";;  # Video 360p
		3) printf '%s \"best[height<=480]\"\n' "${command}";;  # Video 480p
		4) printf '%s \"best[height<=720]\"\n' "${command}";;  # Video 720p
		5) printf '%s \"best[height<=1080]\"\n' "${command}";; # Video 1080p
		6) printf '%s \"best[height<=2160]\"\n' "${command}";; # Video 2160p
		7) exit 1;;
	esac > "${HOME}/.config/youtube-dl/config"
	youtube-dl "${1}"
fi


#There's a cat on the code!!
#          ▄▀▄     ▄▀▄
#         ▄█░░▀▀▀▀▀░░█▄
#     ▄▄  █░░░░░░░░░░░█  ▄▄
#    █▄▄█ █░░█░░┬░░█░░█ █▄▄█

#Oh hey there It's me Oak I have no idea how youtube-dl works but i came across this github and saw the messy code and gave it a better look hope it helps :D

#I wanted to mess a little with the Download code but didn't

#email: Kamilohulau@gmail.com
#Date: Wed Dec  2 15:48:19 PST 2020#
#Project name : Termux-YTD#
#Github: https://github.com/khansaad1275/Termux-YTD#
